### PR TITLE
add hydra module

### PR DESCRIPTION
**Pull request by Knorrke**

### CODE REVIEW

**Comment by aeneasr** [comment]
I'd recommend using our helm chart: https://k8s.ory.sh/helm/hydra.html

**Comment by Knorrke** [comment]
Thanks for the tip, will take a look. Is there a specific reason to choose helm over terraform here?

**Comment by aeneasr** [comment]
Yes, our helm chart appropriately configures all things related to ingress, config management, reloading, secrets and mounting of secrets, and so on.

**Comment by Knorrke** [comment]
Updated it to use the helm chart via terraform helm provider. @aeneasr Would be great if you could take a quick look if I made any obvious mistakes :-)

**Pull request merged**
